apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aspireapp1
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/AspireApp1.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

